# Aixo es un comentari tot sol
%
+ - * / ++ = # I aixo es un comentari en una linia
audio switch json script service plays opens closes int string endpoint request say let sleep
{ } ( ) ; :
nomServei nom_servei2 __nomServei3__
1 24 123019823 000123 0 -25
"aixo es un string" "i aixo tambe"
https://www.example.com/hola/adeu
/home/josep/.config/i3/config
